import psycopg2
import pandas as pd
import os
import sys
from datetime import datetime

# --- Configuration ---
POSTGRES_CONN = "dbname=project_alpha user=chuck host=localhost"
RECIPIENT = "hqzhang2@yahoo.com"

# Shares from the initialized model portfolio
SHARES = {
    'XLE': 66, 'XLU': 54, 'XLP': 22, 'GLD': 4,
    'XLF': 34, 'XLC': 12, 'XLI': 8, 'XLB': 23,
    'XLRE': 19, 'XLK': 12, 'XLY': 12
}
CASH = 235.92

# Import email logic
sys.path.append('/Users/chuck/.openclaw/workspace/email-sender')
try:
    from send_email import send_email
except ImportError:
    def send_email(*args): print("Email sender not found. Outputting to console.")

def get_latest_prices_pg():
    """Fetch latest prices from PostgreSQL 18.3"""
    conn = psycopg2.connect(POSTGRES_CONN)
    query = """
    SELECT ticker, adj_close, date 
    FROM daily_prices 
    WHERE date = (SELECT MAX(date) FROM daily_prices)
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    return df.set_index('ticker')['adj_close'].to_dict(), df['date'].iloc[0]

def generate_report():
    prices, report_date = get_latest_prices_pg()
    
    total_value = CASH
    rows = []
    
    # Sort tickers for consistent reporting
    for ticker in sorted(SHARES.keys()):
        share_count = SHARES[ticker]
        price = float(prices.get(ticker, 0))
        pos_value = share_count * price
        total_value += pos_value
        rows.append(f"| {ticker:<5} | {share_count:>6} | ${price:>8.2f} | ${pos_value:>10.2f} |")

    spy_price = float(prices.get('SPY', 0))
    
    report_body = f"""
PROJECT ALPHA: DAILY PORTFOLIO SNAPSHOT (POSTGRES ENGINE)
Date: {report_date}
------------------------------------------------------------
SUMMARY
Total Portfolio Value: ${total_value:,.2f}
Benchmark (SPY) Price: ${spy_price:.2f}
Residual Cash:         ${CASH:.2f}
------------------------------------------------------------
HOLDINGS BREAKDOWN
| Ticker | Shares | Price     | Value       |
| :---   | :---   | :---      | :---        |
""" + "\n".join(rows) + f"""
------------------------------------------------------------
Status: Operational (PostgreSQL 18.3 Backend)
Generated by Chuck / OpenClaw
"""
    return report_body

if __name__ == "__main__":
    try:
        report = generate_report()
        subject = f"Project Alpha: Daily Snapshot ({datetime.now().strftime('%Y-%m-%d')})"
        
        # Inject credentials for this execution block
        os.environ["EMAIL_USER"] = "munger6c@gmail.com"
        os.environ["EMAIL_PASSWORD"] = "vvqwcmdgjyhfpjhp"
        
        send_email(RECIPIENT, subject, report)
        print("Reports engine (PostgreSQL) executed successfully.")
    except Exception as e:
        print(f"PostgreSQL Report Engine Error: {e}")
