import sqlite3
import pandas as pd
import os
import sys
from datetime import datetime

# Import the existing email sending logic
sys.path.append('/Users/chuck/.openclaw/workspace/email-sender')
from send_email import send_email

# --- Configuration ---
DATABASE_PATH = '/Users/chuck/.openclaw/workspace/sector_etfs.db'
RECIPIENT = "hqzhang2@yahoo.com"
PORTFOLIO_FILE = '/Users/chuck/.openclaw/workspace/2K_Alpha_POC_model_portfolio.md'

# Shares from the initialized model portfolio
SHARES = {
    'XLE': 66, 'XLU': 54, 'XLP': 22, 'GLD': 4,
    'XLF': 34, 'XLC': 12, 'XLI': 8, 'XLB': 23,
    'XLRE': 19, 'XLK': 12, 'XLY': 12
}
CASH = 235.92

def get_latest_prices():
    conn = sqlite3.connect(DATABASE_PATH)
    query = """
    SELECT ticker, adj_close, date 
    FROM daily_prices 
    WHERE date = (SELECT MAX(date) FROM daily_prices)
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    return df.set_index('ticker')['adj_close'].to_dict(), df['date'].iloc[0]

def generate_report():
    prices, report_date = get_latest_prices()
    
    total_value = CASH
    rows = []
    
    for ticker, share_count in SHARES.items():
        price = prices.get(ticker, 0)
        pos_value = share_count * price
        total_value += pos_value
        rows.append(f"| {ticker:<5} | {share_count:>6} | ${price:>8.2f} | ${pos_value:>10.2f} |")

    # Benchmarking
    spy_price = prices.get('SPY', 1)
    
    report_body = f"""
PROJECT ALPHA: DAILY PORTFOLIO SNAPSHOT
Date: {report_date}
------------------------------------------------------------
SUMMARY
Total Portfolio Value: ${total_value:,.2f}
Benchmark (SPY) Price: ${spy_price:.2f}
Residual Cash:         ${CASH:.2f}
------------------------------------------------------------
HOLDINGS BREAKDOWN
| Ticker | Shares | Price     | Value       |
| :---   | :---   | :---      | :---        |
""" + "\n".join(rows) + f"""
------------------------------------------------------------
Status: Operational (Strategy V1.1)
Generated by Chuck / OpenClaw
"""
    return report_body

if __name__ == "__main__":
    try:
        report = generate_report()
        subject = f"Project Alpha: Daily Snapshot ({datetime.now().strftime('%Y-%m-%d')})"
        
        # Verify environment variables (provided in session but need to be passed to script)
        # Note: In production, these should be in the shell environment.
        # For this execution, we assume the host has them or we pass them in the exec call.
        send_email(RECIPIENT, subject, report)
        print("Report engine executed and email sent.")
    except Exception as e:
        print(f"Report Engine Error: {e}")
